# Generated by Django 5.0.2 on 2024-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, verbose_name='url')),
                ('data', models.TextField(verbose_name='data')),
                ('ip', models.CharField(max_length=1000, verbose_name='ip Address')),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
