# Generated by Django 5.0.2 on 2024-03-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, verbose_name='url')),
                ('redirect_url', models.CharField(max_length=1000, verbose_name='Redirect Url')),
                ('form_id', models.CharField(max_length=100, verbose_name='Form ID')),
                ('btn_id', models.CharField(max_length=100, verbose_name='Button ID')),
                ('username_id_name', models.CharField(max_length=100, verbose_name='Username Field ID Or Name')),
                ('password_id_name', models.CharField(max_length=100, verbose_name='Password Filed ID Or Name')),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
